name: Main branch flow for Inventory checker
run-name: ${{ github.actor }} main branch push
on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    snyk-scan:
        runs-on: ubuntu-latest
        env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
            SARIF_FOLDER: sarif-results
        steps:
            -
                name: Check out repository code
                uses: actions/checkout@v3
            -
                name: Installing python
                uses: actions/setup-python@v4
                with:
                    python-version: '3.10'
                    cache: 'pip'
            -
                name: Installing dependencies
                run: |
                  python3 -m pip install -r app/requirements.txt
            - uses: snyk/actions/setup@master
            -
                run: |
                  snyk test --sarif-file-output=${{env.SARIF_FOLDER}}/snyk.sarif --all-projects
            -
                name: Snyk Code test
                run: |
                  snyk code test --all-projects --sarif-file-output=${{env.SARIF_FOLDER}}/snyk-code.sarif || true
            -
                name: Upload open source dependencies analysis result to GitHub Code Scanning
                uses: github/codeql-action/upload-sarif@v2
                with:
                    sarif_file: ${{env.SARIF_FOLDER}}
                    category: dependencies-open-source
            -
                name: configure aws credentials
                uses: aws-actions/configure-aws-credentials@v1.7.0
                with:
                    role-to-assume: ${{ vars.CICD_ROLE}}
                    role-session-name: GitHub_to_AWS_via_FederatedOIDC
                    aws-region: ${{ vars.TF_VAR_AWS_REGION }}
            -
                name: Terraform setup
                uses: hashicorp/setup-terraform@v2
            -
                name: Backend setup and terraform init
                run: |
                      echo 'bucket = "${{ vars.BACKEND_BUCKET_NAME }}" > backend.conf'
                      echo 'key    = "${{ vars.BACKEND_KEY }}" >> backend.conf'
                      echo 'region = "${{ vars.TF_VAR_AWS_REGION }}" >> backend.conf'
                      terraform init -backend-config="bucket=${{ vars.BACKEND_BUCKET_NAME }}" -backend-config="key=${{ vars.BACKEND_KEY }}" -backend-config="region=${{ vars.TF_VAR_AWS_REGION }}"
            -
                name: Terraform plan
                run: |
                      terraform plan
            -
                name: Terraform apply
                run: |
                      terraform plan -auto-approve
