name: Main branch flow for Inventory checker
run-name: ${{ github.actor }} main branch push
on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    snyk-scan:
        runs-on: ubuntu-latest
        steps:
            -
                name: Check out repository code
                uses: actions/checkout@v3
            -
                name: Installing python
                uses: actions/setup-python@v4
                with:
                    python-version: '3.10'
                    cache: 'pip'
            - run: |
                cd app
                python3 -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
            -
                name: Run Snyk for python
                uses: snyk/actions/python-3.10@master
                env:
                    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
                with:
                    args: --sarif-file-output=snyk.sarif --file=/github/workspace/app/requirements.txt
            -
                name: Upload result to GitHub Code Scanning
                uses: github/codeql-action/upload-sarif@v2
                with:
                    sarif_file: snyk.sarif